### ISSUE TITLE
Mobile style tweaks for /roar

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/frontend#132]
- [ ] Dots not centered vertically
- [ ] "Bring attention" text flows onto second line
- [ ] copyright in footer overflows onto second line
- [ ] Video Section too tall in portrait mode
- [ ] Landscape on mobile - video overflows
- [ ] Subscribe to get updates - styling is weird when we get the results
- [ ] Switching from landscape back to portrait leaves ugly white space in the video section

**Comment by shachar-langer** [comment]
> Dots not centered vertically
They are being centered
